#!/bin/bash

COMMIT_MESSAGE="miscellaneous changes"

if [[ $# -eq 1 ]] ; then
    COMMIT_MESSAGE="${1}"
fi

set -x

# commit and push
git add -A .
git commit -m "${COMMIT_MESSAGE}"
git push origin master

# deploy to CapRover
caprover deploy -d
